### ISSUE TITLE
built-in tools crash if user `Bestuur` is not registered

### ISSUE THREAD

**Issue by xopr** [ACKspace/ACKbar#8]
When running either `tool_products.py` or `tool_kastelling.py` for the first time (without/empty database), the program will crash.

### Steps to reproduce
* clear or remove database
* A) start `python3 ./tool_products.py`
* B) start `python3 ./tool_kastelling.py`
 
### Expected result
* A) tool starts and displays product menu
* B) tool starts and displays cash audit menu
 
### Current result
* A) tool instantly crashes:
```
Traceback (most recent call last):
  File "tool_products.py", line 13, in <module>
    admin = session.query(User).filter(User.name=="Bestuur")[0]
  File "/home/xopr/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2652, in __getitem__
    return orm_util._getitem(
  File "/home/xopr/.local/lib/python3.8/site-packages/sqlalchemy/orm/util.py", line 2149, in _getitem
    return list(iterable_query[item : item + 1])[0]
IndexError: list index out of range
```
* B) tool crashes after providing two entries:
```
ACKbar geeft aan dat er (minstens) 0.00 in de kas moet liggen
Hoeveel ligt er: 0
Hoeveel geld afromen: 0
Traceback (most recent call last):
  File "tool_kastelling.py", line 25, in <module>
    session.add(KasMutatie(mutatiesoort=KasMutatieSoort.correctie, user_id=user[0].id, bedrag=correctie))
  File "/home/xopr/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2652, in __getitem__
    return orm_util._getitem(
  File "/home/xopr/.local/lib/python3.8/site-packages/sqlalchemy/orm/util.py", line 2149, in _getitem
    return list(iterable_query[item : item + 1])[0]
IndexError: list index out of range
```

### Workaround
* register user `Bestuur`

**Comment by Prodigity** [comment]
Fixed with PR #13
